spring.application.name=myshop

# 1. 指定要連向本機電腦 3306 大門的 sys 資料庫大箱子
spring.datasource.url=jdbc:mysql://localhost:3306/sys
# 2. 登入的最高管理者帳號與你的嚴謹密碼
spring.datasource.username=root
spring.datasource.password=King929523@
# 3. 自動載入驅動字典
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 🌟 核心開關：update 的意思是，只要 Java 裡有新的 @Entity，開機時自動去 MySQL 建表/更正表！
spring.jpa.hibernate.ddl-auto=update
# 讓 Spring Boot 貼心地在黑色終端機把他在背後幫你手寫的 SQL 印出來給你看
spring.jpa.show-sql=true